<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-11T22:54:36 IST" name="Suite" finished-at="2025-05-11T22:54:44 IST" duration-ms="8641">
    <groups>
    </groups>
    <test started-at="2025-05-11T22:54:36 IST" name="Test" finished-at="2025-05-11T22:54:44 IST" duration-ms="8641">
      <class name="puransinh.Test.LoginTest">
        <test-method is-config="true" signature="initDriver()[pri:0, instance:puransinh.Test.LoginTest@1224144a]" started-at="2025-05-11T22:54:36 IST" name="initDriver" finished-at="2025-05-11T22:54:39 IST" duration-ms="3288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="inValidUser()[pri:0, instance:puransinh.Test.LoginTest@1224144a]" started-at="2025-05-11T22:54:39 IST" name="inValidUser" finished-at="2025-05-11T22:54:39 IST" duration-ms="442" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inValidUser -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:puransinh.Test.LoginTest@1224144a]" started-at="2025-05-11T22:54:40 IST" name="closeBrowser" finished-at="2025-05-11T22:54:40 IST" duration-ms="562" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="initDriver()[pri:0, instance:puransinh.Test.LoginTest@1224144a]" started-at="2025-05-11T22:54:40 IST" name="initDriver" finished-at="2025-05-11T22:54:43 IST" duration-ms="2575" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method signature="validUser()[pri:0, instance:puransinh.Test.LoginTest@1224144a]" started-at="2025-05-11T22:54:43 IST" name="validUser" finished-at="2025-05-11T22:54:43 IST" duration-ms="677" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Hello World] but found [Let's Shop]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Hello World] but found [Let's Shop]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at puransinh.Test.LoginTest.validUser(LoginTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUser -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:puransinh.Test.LoginTest@1224144a]" started-at="2025-05-11T22:54:44 IST" name="closeBrowser" finished-at="2025-05-11T22:54:44 IST" duration-ms="601" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- puransinh.Test.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
